name: Verify lint

on: push

jobs:
  verify_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version: 20.10
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Verify lint
        run: npm lint

      # - name: Build
      #   run: npm build
