name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Verify lint
        run: npm lint

      - name: Run cypress e2e
        run: npm run cy:e2e

      # - name: Build
      #   run: npm build

      # Deployment to hosting
